// Autogenerated - do NOT edit!
// VertexShader: PosUv0RectTileCoverage
$input v_uv0, v_coverage, v_rect, v_tile
#define PAINT_PATTERN
#define MIRRORU_PATTERN
#define EFFECT_PATH_AA
#include "FSMain.ishader"
