// Autogenerated - do NOT edit!
$input a_position, a_color0, a_texcoord0, a_texcoord2, a_texcoord4
$output v_color0, v_uv0, v_rect, v_imagePos
#define HAS_COLOR
#define HAS_UV0
#define HAS_RECT
#include "VSMain.ishader"
