// Autogenerated - do NOT edit!
$input a_position, a_texcoord0, a_texcoord2, a_texcoord3, a_texcoord5
$output v_uv0, v_rect, v_tile, v_coverage
#define HAS_UV0
#define HAS_RECT
#define HAS_TILE
#define HAS_COVERAGE
#include "VSMain.ishader"
