// Autogenerated - do NOT edit!
$input a_position, a_texcoord0, a_texcoord1, a_texcoord2, a_texcoord3
$output v_uv0, v_uv1, v_rect, v_tile
#define HAS_UV0
#define HAS_UV1
#define HAS_RECT
#define HAS_TILE
#include "VSMain.ishader"
