// Autogenerated - do NOT edit!
// VertexShader: PosUv0Uv1RectTileSdf
$input v_uv0, v_uv1, v_st1, v_rect, v_tile
#define PAINT_PATTERN
#define MIRROR_PATTERN
#define EFFECT_SDF_LCD
#include "FSMain.ishader"
