// Autogenerated - do NOT edit!
#pragma once
#include <string_view>
constexpr std::string_view VertexVersion {"Thursday, April 28, 2022"};
constexpr std::string_view VertexShaders[]
{
	"Pos",
	"PosColor",
	"PosUv0",
	"PosUv0Rect",
	"PosUv0RectTile",
	"PosColorCoverage",
	"PosUv0Coverage",
	"PosUv0RectCoverage",
	"PosUv0RectTileCoverage",
	"PosColorUv1Sdf",
	"PosUv0Uv1Sdf",
	"PosUv0Uv1RectSdf",
	"PosUv0Uv1RectTileSdf",
	"PosColorUv1",
	"PosUv0Uv1",
	"PosUv0Uv1Rect",
	"PosUv0Uv1RectTile",
	"PosColorUv0Uv1",
	"PosUv0Uv1Downsample",
	"PosColorUv1Rect",
	"PosColorUv0RectImagePosition",
};
