include(FetchContent)

set(ALSOFT_INSTALL OFF CACHE BOOL "" FORCE)
set(ALSOFT_UTILS OFF CACHE BOOL "" FORCE)
set(ALSOFT_EXAMPLES OFF CACHE BOOL "" FORCE)
set(ALSOFT_INSTALL_EXAMPLES OFF CACHE BOOL "" FORCE)
set(ALSOFT_INSTALL_UTILS OFF CACHE BOOL "" FORCE)
set(ALSOFT_UPDATE_BUILD_VERSION OFF CACHE BOOL "" FORCE)
FetchContent_Declare(
        OpenALSoft
        GIT_REPOSITORY "https://github.com/kcat/openal-soft.git"
        GIT_TAG "1.22.2"
        GIT_SHALLOW ON
)
FetchContent_MakeAvailable(OpenALSoft)
