//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ingnomia.Localization {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IngnomiaGUI.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FR_RES_MainPage_Continue.
        /// </summary>
        public static string MainPage_Continue {
            get {
                return ResourceManager.GetString("MainPage_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FR_MainPage_Exit.
        /// </summary>
        public static string MainPage_Exit {
            get {
                return ResourceManager.GetString("MainPage_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FR_MainPage_Hint_MMContinue.
        /// </summary>
        public static string MainPage_Hint_MMContinue {
            get {
                return ResourceManager.GetString("MainPage_Hint_MMContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FR_MainPage_Hint_MMExit.
        /// </summary>
        public static string MainPage_Hint_MMExit {
            get {
                return ResourceManager.GetString("MainPage_Hint_MMExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FR_MainPage_Hint_MMLoadGame.
        /// </summary>
        public static string MainPage_Hint_MMLoadGame {
            get {
                return ResourceManager.GetString("MainPage_Hint_MMLoadGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FR_MainPage_Hint_MMNewGame.
        /// </summary>
        public static string MainPage_Hint_MMNewGame {
            get {
                return ResourceManager.GetString("MainPage_Hint_MMNewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FR_MainPage_Hint_MMSettings.
        /// </summary>
        public static string MainPage_Hint_MMSettings {
            get {
                return ResourceManager.GetString("MainPage_Hint_MMSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FR_MainPage_Hint_MMSetupGame.
        /// </summary>
        public static string MainPage_Hint_MMSetupGame {
            get {
                return ResourceManager.GetString("MainPage_Hint_MMSetupGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FR_RES_MainPage_Ingnomia.
        /// </summary>
        public static string MainPage_Ingnomia {
            get {
                return ResourceManager.GetString("MainPage_Ingnomia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FR_MainPage_LoadGame.
        /// </summary>
        public static string MainPage_LoadGame {
            get {
                return ResourceManager.GetString("MainPage_LoadGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FR_MainPage_NewGame.
        /// </summary>
        public static string MainPage_NewGame {
            get {
                return ResourceManager.GetString("MainPage_NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FR_MainPage_Settings.
        /// </summary>
        public static string MainPage_Settings {
            get {
                return ResourceManager.GetString("MainPage_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FR_MainPage_SetUpGame.
        /// </summary>
        public static string MainPage_SetUpGame {
            get {
                return ResourceManager.GetString("MainPage_SetUpGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FR_SettingsPage_Accept.
        /// </summary>
        public static string SettingsPage_Accept {
            get {
                return ResourceManager.GetString("SettingsPage_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FR_SettingsPage_Back.
        /// </summary>
        public static string SettingsPage_Back {
            get {
                return ResourceManager.GetString("SettingsPage_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FR_SettingsPage_Controls.
        /// </summary>
        public static string SettingsPage_Controls {
            get {
                return ResourceManager.GetString("SettingsPage_Controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FR_SettingsPage_FullScreen.
        /// </summary>
        public static string SettingsPage_FullScreen {
            get {
                return ResourceManager.GetString("SettingsPage_FullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FR_SettingsPage_Game.
        /// </summary>
        public static string SettingsPage_Game {
            get {
                return ResourceManager.GetString("SettingsPage_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FR_SettingsPage_KeyboardSpeed.
        /// </summary>
        public static string SettingsPage_KeyboardSpeed {
            get {
                return ResourceManager.GetString("SettingsPage_KeyboardSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FR_SettingsPage_Language.
        /// </summary>
        public static string SettingsPage_Language {
            get {
                return ResourceManager.GetString("SettingsPage_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FR_SettingsPage_LightMin.
        /// </summary>
        public static string SettingsPage_LightMin {
            get {
                return ResourceManager.GetString("SettingsPage_LightMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FR_res_SettingsPage_Settings.
        /// </summary>
        public static string SettingsPage_Settings {
            get {
                return ResourceManager.GetString("SettingsPage_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FR_SettingsPage_UiScale.
        /// </summary>
        public static string SettingsPage_UiScale {
            get {
                return ResourceManager.GetString("SettingsPage_UiScale", resourceCulture);
            }
        }
    }
}
