name: Docs

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pipenv
        run: pip install pipenv

      - name: Download Tilesheets
        shell: bash
        run: |
          curl -L -o tilesheet.zip https://github.com/rschurade/IngnomiaBuildDeps/raw/master/tilesheet.zip
          mkdir -p content
          unzip -o tilesheet.zip -d content

      - name: Setup venv
        working-directory: docs
        run: pipenv install --skip-lock

      - name: Generate docs
        working-directory: docs
        run: pipenv run ./generate.py --build ${GITHUB_REF#refs/*/}

      - name: Deploy docs to gh-pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          keep_history: true
          build_dir: docs/html
          fqdn: ${{ secrets.DOCS_DOMAIN }}
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
